# Generated by Django 4.1.13 on 2025-02-14 02:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Film",
            fields=[
                ("film_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("attributes", models.JSONField(blank=True, null=True)),
                ("attributes_orig", models.JSONField(blank=True, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Film",
                "verbose_name_plural": "Films",
                "db_table": "film",
                "ordering": ["title"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="FilmCharacter",
            fields=[
                ("film_character_id", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "verbose_name": "Film Character",
                "verbose_name_plural": "Film Characters",
                "db_table": "film_character",
                "ordering": ["film", "sentient_being"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="FilmPlanet",
            fields=[
                ("film_planet_id", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "verbose_name": "Film Planet",
                "verbose_name_plural": "Film Planets",
                "db_table": "film_planet",
                "ordering": ["film", "planet"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="FilmVehicle",
            fields=[
                ("film_vehicle_id", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "verbose_name": "Film Vehicle",
                "verbose_name_plural": "Film Vehicless",
                "db_table": "film_vehicle",
                "ordering": ["film", "vehicle"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                ("language_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("attributes", models.JSONField(blank=True, null=True)),
                ("attributes_orig", models.JSONField(blank=True, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Language",
                "verbose_name_plural": "Languages",
                "db_table": "language",
                "ordering": ["name"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Planet",
            fields=[
                ("planet_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("attributes", models.JSONField(blank=True, null=True)),
                ("attributes_orig", models.JSONField(blank=True, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Planet",
                "verbose_name_plural": "Planets",
                "db_table": "planet",
                "ordering": ["name"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SentientBeing",
            fields=[
                ("sentient_being_id", models.AutoField(primary_key=True, serialize=False)),
                ("name_first", models.CharField(max_length=100)),
                ("name_last", models.CharField(max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("attributes", models.JSONField(blank=True, null=True)),
                ("attributes_orig", models.JSONField(blank=True, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Sentient Being",
                "verbose_name_plural": "Sentient Beings",
                "db_table": "sentient_being",
                "ordering": ["name_last", "name_first"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SentientBeingType",
            fields=[
                ("sentient_being_type_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("attributes", models.JSONField(blank=True, null=True)),
                ("attributes_orig", models.JSONField(blank=True, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Sentient Being Type",
                "verbose_name_plural": "Sentient Being Types",
                "db_table": "sentient_being_type",
                "ordering": ["name"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                ("vehicle_id", models.AutoField(primary_key=True, serialize=False)),
                ("model", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("attributes", models.JSONField(blank=True, null=True)),
                ("attributes_orig", models.JSONField(blank=True, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Vehicle",
                "verbose_name_plural": "Vehicles",
                "db_table": "vehicle",
                "ordering": ["model"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VehicleClass",
            fields=[
                ("vehicle_class_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("attributes", models.JSONField(blank=True, null=True)),
                ("attributes_orig", models.JSONField(blank=True, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Vehicle Class",
                "verbose_name_plural": "Vehicle Classes",
                "db_table": "vehicle_class",
                "ordering": ["name"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VehicleType",
            fields=[
                ("vehicle_type_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("attributes", models.JSONField(blank=True, null=True)),
                ("attributes_orig", models.JSONField(blank=True, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Vehicle Type",
                "verbose_name_plural": "Vehicle Types",
                "db_table": "vehicle_type",
                "ordering": ["name"],
                "managed": False,
            },
        ),
    ]
